export const GET_WISHLISTS = "GET_WISHLISTS";
export const GET_USER_IDEAS = "GET_USER_IDEAS";
export const AUTH_START = "AUTH_START";
export const AUTH_PASSED = "AUTH_PASSED";
export const AUTH_FAILED = "AUTH_FAILED";

export const LOGIN_START = "LOGIN_START";

export const GET_USER_DETAILS = "GET_USER_DETAILS";
export const POST_USER_DETAILS = "POST_USER_DETAILS";
export const POST_SUCCESS = "POST_SUCCESS";

/****************Post wislists Actions***********/
export const POST_WISHLIST = "POST_WISHLIST";
export const POST_WISHLIST_SUCCESS = "POST_WISHLIST_SUCCESS";
export const POST_WISHLIST_FAILED = "POST_WISHLIST_FAILED";

export const FETCH_WISHLISTS = "FETCH_WISHLISTS";
export const FETCH_WISHLISTS_SUCCESS = "FETCH_WISHLIST_SUCCESS";
export const FETCH_WISHLISTS_FAILED = "FETCH_WISHLIST_FAILED";

export const DELETE_WISHLISTS = "DELETE_WISHLISTS";
export const DELETE_WISHLISTS_SUCCESS = "DELETE_WISHLIST_SUCCESS";
export const DELETE_WISHLISTS_FAILED = "DELETE_WISHLIST_FAILED";
